### PR TITLE
Ra2b v12 v0

### PR DESCRIPTION
**Pull request by rpatelCERN**
Hey Andrew, 
I patched up  a few pieces of code:
Updated the Alphabet code for trigger weights. 
I added a few modifications to the skimSamples. 
I also rewrote the datacard builder and added a file for Trigger efficiency computation

### CODE REVIEW

**Comment by rpatelCERN** [comment]
Also added all the signal files, so they are included in the datacards file.

**Comment by rpatelCERN** [comment]
I also finished up the datacard code, which will take the output datacardinputs and turn them into text files for the combine tool

**Comment by awhitbeck** [comment]
I don't know what happened with this PR, but there are  a lot of files that are "changed", but don't have a diff.   Is there any way you can drop these changes, for example `src/baselineSkims.cc` is in the file changed list, but there is nothing different.  I would just like to avoid destroying the history so that we can track things. 

Also can you commit just the code for the datacard inputs for now?  Probably, we'll commit the cards somewhere, but maybe lets wait.  In the very least, i would like to merge them separately.

**Comment by awhitbeck** [comment]
so is this dead?

**Comment by awhitbeck** [comment]
addressed in another PR

**Pull request closed without merging**
